### ISSUE TITLE
jQuery is a NO!

### ISSUE THREAD

**Issue by farooqkz** [mohsenfaraj/AzmoonYaar#1]
Just a friendly reminder, better base your web app on something modern and not almost deprecated ;)

**Comment by mohsenfaraj** [comment]
Hello, Thanks a lot for your comment on this project. it means a lot...
this is a university assignment and we **had** to use JQuery. I'm aware that JQuery is an old technology (even though it is still widely used) but i had no choice.
for personal projects i use react. thanks for your friendly reminder :)

**Comment by farooqkz** [comment]
> Hello, Thanks a lot for your comment on this project. it means a lot... this is a university assignment and we **had** to use JQuery. I'm aware that JQuery is an old technology (even though it is still widely used) but i had no choice. for personal projects i use react. thanks for your friendly reminder :)

oh I see! Unis are usually sources of evil! In which uni are you doing your study?

BTW, you closed this issue as completed. You had to close it as "not planned".

**Comment by mohsenfaraj** [comment]
>In which uni are you doing your study?

Urmia University of Technology, but i think all universities are same... you can't keep up with new technologies in universities. it's a rare occasion specially in Iran.
>BTW, you closed this issue as completed. You had to close it as "not planned".

oh ok... sorry! :grin:
